### ISSUE TITLE
 im getting this error

### ISSUE THREAD

**Issue by developerfranso** [DITTeamProject/Movie_Rental_Management_System#23]
Warning: require_once(DB.php): failed to open stream: No such file or directory in C:\xampp\htdocs\DVD\Database\DBManager.php on line 2

**Comment by Jamesxu182** [comment]
Dear Developer

This Project dependent on Pear DB to manage and operate databases, which is a third part library in PHP.  You got the error because you miss installing Pear DB.

[Pear DB Website](http://pear.php.net/package/DB/redirected)

You can briefly install Pear DB with the command below
``` bash
http://pear.php.net/package/DB/redirected
```

Hope me answer could help you.

Best Regards
Yifan Xu

**Comment by developerfranso** [comment]
Thank so much i have just installed the Pear DB i now get the following error   "DB Error: no such table"

**Comment by Jamesxu182** [comment]
Dear Developer

You got this error because you don't create table on you computer. you can find the sql file follow this path Movie_Rental_Management_System/database/database.sql. you can run the sql code in mysql workbeech and the tables will be created.

Best Regards
Yifan Xu

**Comment by Jamesxu182** [comment]
Dear Developer 

Please double check the following configure file. Movie_Rental_Management_System/Config/config.inc.php. you should create a database and a create a user according to the file. just make sure the database could be accessed from local first.

Hope it helpful and handy

Best Regards
Yifan Xu

**Comment by developerfranso** [comment]
thanks so helpfull
